project:
  type: website
  output-dir: docs

website:
  title: "Megan Zelinsky"
  description: ""
  image: images/Headshot2021.jpg
  favicon: images/favicon.png
  
  navbar:
    pinned: true
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: research.qmd
        text: Research Interests
      - href: cv.qmd
        text: Curriculum Vitae
      - href: publications.qmd
        text: Recent Publications
      - href: ccp.qmd
        text: Community Engagement

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/megan-zelinsky-0468321b5/
      - icon: envelope
        aria-label: email
        href: "mailto:meganezelinsky@gmail.com"  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

