---
title: "About Me"
---

I work in the Center for Neurological Restoration at Cleveland Clinic Neurological Institute, where I collaborate on patient-centered research studies, conduct qualitative analyses, and integrate neuroethics into our research infrastructure. My work often explores ethical challenges in clinical and research settings, with a focus on vulnerable populations and novel neurosurgical procedures.

I hold a Master’s degree in Bioethics and Medical Humanities from Case Western Reserve University School of Medicine, where I completed over 240 hours of clinical and ethics rotations in Cleveland-area healthcare systems. My training focused on ethical issues impacting patients with neurological disease and included research ethics, study design, and empirical bioethics methods.

In addition to my research, I have lectured at both undergraduate and graduate levels and mentored students pursuing careers in clinical research and bioethics. I am also proud to have completed certifications in standards for clinical data management and clinical project management, which I use to promote the translation of high-quality research into meaningful outcomes for patients.

Outside of work, I lead the Cleveland Community Cat Project as Executive Director, where I apply evidence-based approaches to support feline welfare and community partnerships. When I’m not working, you can find me fostering kittens, practicing yoga, or reading.
