---
title: "Curriculum Vitae"
subtitle: "Current as of: July 2025"
---

Below is an overview of my education, research experience, and professional contributions. You can also download a complete version of my CV for more details.

[Download CV](files/2024-03-megan-zelinsky-cv.pdf){.btn .btn-primary}

# Megan Zelinsky, MA, BS

# Education

-   **PhD, Clinical Translational Science**, expected 2027\
    Dissertation in progress: “Bridging Translational Science and Empirical Neuroethics to Align Neurosurgical Metrics with Patient-Centered Outcomes”\
    Research focus: Translational neuroethics and patient-centered outcome selection in neurosurgery\
    Case Western Reserve University, Cleveland, OH\
    *2024 - Present*

-   **MA, Bioethics and Medical Humanities**\
    Capstone: "High-Intensity Focused Ultrasound for Parkinson Disease: Ethical Considerations in an Evolving Treatment Landscape"\
    Case Western Reserve University, Cleveland, OH\
    *2019 - 2020*

-   **BS, Biological Sciences**, *summa cum laude*\
    University of Pittsburgh, Pittsburgh, PA\
    *2015 - 2018*

# Employment

## Research

-   **Clinical Research Project Manager**\
    Center for Neurological Restoration, Neurological Institute, Cleveland Clinic, Cleveland, OH\
    *2020 - Present*

## Teaching

-   **Lecturer**\
    Columbia University, New York, NY\
    *2020 - 2023*

-   **Adjunct Faculty**\
    Case Western Reserve University, Cleveland, OH\
    *2022 - 2022*

-   **Adjunct Faculty**\
    Capital University, Columbus, OH\
    *2020 - 2022*

## Animal Welfare

-   **Executive Director**\
    Cleveland Community Cat Project, Cleveland, OH\
    *2018 - Current*

# Professional Activities

## Editorial Board

-   **Journal of Disability and Health** *(2024 - Present)*

## Ad Hoc Peer Review

-   Journal of Disability and Health
-   Journal of Bioethical Inquiry

## Membership in Professional Societies

-   International Neuroethics Society
-   Society of Clinical Research Associates
-   American Society for Bioethics and Humanities

# Research and Quality Improvement Activities

-   **“Evaluating Multidisciplinary Impact on Epilepsy Surgical Recommendations: A Quality Improvement Initiative Using Pre/Post Polling at Patient Management Conferences \[QA/QI\]”**\
    Role: Collaborator\
    *July 2025 - Present*

-   **“Center for Neurological Restoration Functional Neurological Disorder Clinical Database \[QA/QI\]”**\
    Role: Database Manager\
    Funding: Philanthropy\
    *Feb 2025 - Present*

-   **“Provider Perspectives on the Use of Genetic Profiling in Deep Brain Stimulation Evaluation for Parkinson’s Disease”**\
    Role: Co-investigator\
    Funding: internal\
    PI: Hubert Fernandez\
    *Jan 2025 - Present*

-   **“LGBTQ+ Inclusive Communication and Advance Care Planning”**\
    Role: Data Analyst\
    Funding: Advancing Interprofessional Learning Grant (EHEZ013)\
    PI: Georgina Morley, PhD\
    *Jan 2024 - July 2025*

-   **“Novel Care Model for Treatment of Functional Movement Disorders: A Mixed-Methods Study Investigating the Role of Virtual Shared Medical Appointments”**\
    Role: Co-investigator\
    Funding: Cleveland Clinic Healthcare Delivery and Implementation Science Center\
    PI: Xin Xin Yu, MD\
    *Dec 2023 – Present*

-   **“Building Consensus on Disclosure of Preclinical Data in Early Phase Exploratory Research Involving Human Neurotechnology”**\
    Role: Project Manager\
    Funding: National Center for Complementary and Integrative Health, 3R01AT011905-02S1\
    PI: Lauren Sankary, JD\
    *Aug 2023 – Present*

-   **“A Cognitive Risk Calculator and Screening Tool for Primary Care Settings”**\
    Role: Project Manager\
    Funding: National Institutes of Health, Mechanism R33 (4R33AG069729-03)\
    PI: Darlene Floden, PhD\
    *Jun 2022 – Present*

-   **“Cognitive Outcomes of Magnetic Resonance-Guided Focused Ultrasound Neurosurgery”**\
    Role: Project Manager\
    Funding: Internal\
    PI: Darlene Floden, PhD\
    *Feb 2022 – Present*

-   **“Center for Functional and Restorative Neuroscience Neuropsychology Registry”**\
    Role: Database Manager\
    Funding: Internal\
    PI: Darlene Floden, PhD\
    *Oct 2021 – Present*

-   **“Optimizing Decision Support and Return of Results in Neurological Research”**\
    Role: Project Manager\
    Funding: Internal\
    PI: Lauren Sankary, JD\
    *Oct 2021 – Present*

-   **“Optimizing Decision Support for Alzheimer’s Disease Research Participants”**\
    Role: Project Manager\
    Funding: Alzheimer’s Association Research Grant (AARG-22-974462)\
    PI: Lauren Sankary, JD\
    *Jun 2021 – Present*

-   **“Neuroethics Database for Ethics Consultations Involving Elective Neurosurgical Candidates”**\
    Role: Database Manager\
    Funding: Parkinson Foundation\
    PI: Lauren Sankary, JD\
    *Apr 2021 – Present*

-   **“Responding to Ethical Issues during the COVID-19 Pandemic: Operationalizing Nurses’ Insights to Develop Ethical Resilience (RESPONDER Project)”**\
    Role: Study Coordinator\
    Funding: Pending\
    PI: Georgina Morley, PhD\
    *Mar 2021 – Dec 2022*

-   **“A Statistical Scoring Tool to Optimize Preclinical Research”**\
    Role: Study Coordinator\
    Funding: Cleveland Clinic Neurological Institutes Innovation and Discovery (NIID) Award (2019-334)\
    PI: Olivia Hogue, PhD, MPH\
    *Sep 2020 – Present*

-   **“COVID-19 Related Barriers to Informed Consent in Aging and Cognitively Vulnerable Patients”**\
    Role: Study Coordinator\
    Funding: National Institute on Aging (NIA), Mechanism P30 (P30AG062428-02S2)\
    PI: Lauren Sankary, JD\
    *Aug 2020 – Jun 2022*

-   **“Overcoming Unanticipated Barriers to Informed Consent in Brain Research”**\
    Role: Research Assistant\
    Funding: National Institute of Neurological Disorders and Stroke (NINDS), Mechanism UH3 (3UH3NS100543-03S1)\
    PI: Lauren Sankary, JD\
    *Mar 2020 – Present*

-   **“Ethical Safeguards for Exit and Withdrawal from Implanted Neurotechnology Research”**\
    Role: Research Assistant\
    Funding: National Institute of Neurological Disorders and Stroke (NINDS), Mechanism F32 (1F32MH115419-01)\
    PI: Lauren Sankary, JD\
    *Mar 2020 – Jun 2021*

# Teaching Activities

-   **Instructor**\
    Neuroscience and Ethics (3-credit graduate course)\
    Columbia University, New York, NY\
    *(Summer 2023)*

-   **Lecturer**\
    Inclusivity & Accessibility of Neurotechnology (lecture in Foundations of Bioethics II, 6-credit graduate course)\
    Case Western Reserve University, Cleveland, OH\
    *(Spring 2022)*

-   **Instructor**\
    Theoretical Ethics and Ethical Argumentation (3-credit undergraduate course)\
    Capital University, Columbus, OH\
    *(Spring 2022)*

-   **Lecturer**\
    Unit in Neuroethics (3-credit graduate course)\
    Case Western Reserve University, Cleveland, OH\
    *(Spring 2022)*

-   **Instructor**\
    Theoretical Ethics and Ethical Argumentation (3-credit undergraduate course)\
    Capital University, Columbus, OH\
    *(Fall 2021)*

-   **Teaching Associate**\
    Neuroscience and Ethics (3-credit graduate course)\
    Columbia University, New York, NY\
    *(Summer 2021)*

-   **Instructor**\
    Theoretical Ethics and Ethical Argumentation (3-credit undergraduate course)\
    Capital University, Columbus, OH\
    *(Spring 2021)*

-   **Instructor**\
    Theoretical Ethics and Ethical Argumentation (3-credit undergraduate course)\
    Capital University, Columbus, OH\
    *(Fall 2020)*

-   **Instructor**\
    Introduction to Ethics (3-credit undergraduate course)\
    Capital University, Columbus, OH\
    *(Fall 2020)*

-   **Teaching Associate**\
    Neuroscience and Ethics (3-credit graduate course)\
    Columbia University, New York, NY\
    *(Summer 2020)*

-   **Teaching Assistant**\
    Biochemistry (3-credit undergraduate course)\
    University of Pittsburgh, Pittsburgh, PA\
    *(Fall 2017)*

-   **Teaching Assistant**\
    Genetics (3-credit undergraduate course)\
    University of Pittsburgh, Pittsburgh, PA\
    *(Spring 2017)*

-   **Teaching Assistant**\
    Organic Chemistry II (3-credit undergraduate laboratory course)\
    University of Pittsburgh, Pittsburgh, PA\
    *(Spring 2017)*

-   **Teaching Assistant**\
    Organic Chemistry I (3-credit undergraduate laboratory course)\
    University of Pittsburgh, Pittsburgh, PA\
    *(Spring 2016)*

-   **Teaching Assistant**\
    Biology II (3-credit undergraduate laboratory course)\
    University of Pittsburgh, Pittsburgh, PA\
    *(Fall 2015)*

-   **Teaching Assistant**\
    Biology I (3-credit undergraduate laboratory course)\
    University of Pittsburgh, Pittsburgh, PA\
    *(Spring 2015)*

# Bibliography

For the most up-to-date information, visit my [ORCiD Profile](https://orcid.org/0000-0001-6964-8794) to see my full list of publications.

# Abstracts and Posters

**Zelinsky M,** Anis S, Shuaib U, Hartwig E, Rush TE, Yu XX. Investigating the role of virtual shared medical appointments in functional movement disorder care: Survey study insights. Presented at: 30th World Congress on Parkinson’s Disease and Related Disorders; May 7-10, 2025; New York, NY. Parkinsonism Relat Disord. 2025.

Sankary LR, Rico VR, **Zelinsky M**, Ford P. Capturing Embedded Ethics Contributions in Patient Selection: A Neurosurgical Ethics Database Project. Presented at: Sutter Health Clinical Ethics UnConference; Apr 23-25, San Francisco, California.

Sankary LR, **Zelinsky M**, Webster HS, Lerner AJ, Martinez K, Miller JB, Ford PJ, Leverenz JB. Alzheimer’s Disease Research Participant Perspectives on the Return of Individual Research Results. Poster presented at: AAIC 2022, The Alzheimer’s Association International Conference; 2022 Jul 31-Aug 4, San Diego, California.

Morley G, Copley D, Field R, **Zelinsky M**, Albert N. Responding to Ethical Issues and Operationalizing Nurses Insights to Develop Ethical Resilience. Poster presented at: AACN National Teaching Institute (NTI) & Critical Care Exposition; 2023 May 24, Philadelphia, Pennsylvania.

Morley G, Copley D, Field R, **Zelinsky M**, Albert N. A Divided Community: A Descriptive Qualitative Study of the Impact of COVID-19 on Nurses and their Relationships. Poster presented at: 18th Annual Cleveland Clinic Nursing Research Conference; 2023 Apr 24-25, Cleveland, Ohio.

Morley G, Copley D, Field R, **Zelinsky M**, Albert N. Responding to Ethical Issues during the COVID-19 Pandemic and Operationalizing Nurses Insights to Develop Ethical Resilience (RESPONDER): A Descriptive Qualitative Study. Poster presented at: 2023 ICU Operations Annual Summit; 2023 Mar 16, Cleveland, Ohio.

Sankary LR, **Zelinsky M**, Lindgren L, Ford PJ. Ethical Implications of Neurological Research Consent Adaptations Necessitated by the COVID-19 Pandemic. Abstract presented at: 2022 INS Annual Meeting, International Neuroethics Society: Bringing Neuroethics to Life Throughout Patient Care, Research, and Policy; 2022 Nov 2-4, Montreal, Canada.

Sankary LR, **Zelinsky M**, Knaggs C, Lerner AJ. Alzheimer’s Disease Research Participant Perspectives on the Return of Individual Research Results. Poster presented at: AAIC 2022, The Alzheimer’s Association International Conference; 2022 Jul 31-Aug 4, San Diego, California.

Morley G, Copley D, Field R, **Zelinsky M**, Albert N. Responding to Ethical Issues during the COVID-19 Pandemic and Operationalizing Nurses Insights to Develop Ethical Resilience (RESPONDER): A Descriptive Qualitative Study. Poster presented at: 17th Annual Cleveland Clinic Clinical Nursing Research Conference; 2022 Apr 25-26, Cleveland, Ohio.

# Awards and Honors

-   IAPRD Guided Poster Award: 2025
-   AACN Research Poster Award: 2023
-   99th Percentile in Teaching Evaluations, Capital University: Fall 2020, Spring 2021, Summer 2021, Fall 2021, Spring 2022
-   Dean’s List, University of Pittsburgh: All semesters
-   Best Undergraduate Capstone, University of Pittsburgh, 2017
-   Student Leadership Award, University of Pittsburgh: 2017
-   Student Research Day Best Abstract, University of Pittsburgh: Fall 2016
-   Student Research Day Best Poster Presentation, University of Pittsburgh: Fall 2016, Spring 2017
-   Distinguished Debate Performance, University of Pittsburgh: Fall 2015, Spring 2016, Fall 2017

# Additional Work Experience

-   **Customer Support Supervisor**\
    Aerotek Recruiting and Staffing, Reading, PA\
    *Dec 2011 – Jul 2017*

-   **Customer Support Analyst**\
    Aerotek Recruiting and Staffing, York, PA\
    *Jan 2011 – Dec 2011*

-   **Administrative Assistant**\
    Aerotek Recruiting and Staffing, York, PA\
    *Nov 2010 – Jan 2011*
